name: "ğŸ“¦ CD â€” Publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.repository.fork == false
    name: Release Please
    outputs:
      release_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: ğŸ¤ Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          path: packages/resafe
          release-type: node

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: â• Actions - Checkout
        uses: actions/checkout@v6

      - name: â• Actions - Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: â• Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: bun-linux-${{ hashFiles('packages/resafe/package.json') }}
          restore-keys: bun-linux-

      - name: ğŸ“¦ Installing Dependencies
        run: bun ci

      - name: ğŸš€ Build Package
        run: bun build:package

      - name: ğŸ“¥ Publishing Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/resafe
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish --provenance --access public
